name: Candi CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Unit Test
      run: |
        make test
        bash <(curl -s https://codecov.io/bash)

    - name: Build binary CLI
      run: |
        mkdir candi
        GOOS=linux GOARCH=amd64 go build -o candi/candi-linux cmd/candi/*.go
        GOOS=darwin GOARCH=amd64 go build -o candi/candi-osx cmd/candi/*.go

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: candi
        path: candi
