name: Candi CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Unit Test
      run: |
        make test
        bash <(curl -s https://codecov.io/bash)

    - name: Build binary CLI
      run: |
        GOOS=linux GOARCH=amd64 go build -o candi-linux cmd/candi/*.go
        GOOS=darwin GOARCH=amd64 go build -o candi-osx cmd/candi/*.go

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Setup GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true

      - name: Deploy
        run: |-
          gsutil cp candi-linux gs://agungdp/bin/candi-linux
          gsutil cp candi-osx gs://agungdp/bin/candi-osx
          gsutil acl ch -u AllUsers:R gs://agungdp/bin/candi-linux
          gsutil acl ch -u AllUsers:R gs://agungdp/bin/candi-osx
