name: Candi CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Unit Test
      run: |
        make test
        bash <(curl -s https://codecov.io/bash)

    - name: Build binary CLI
      run: |
        mkdir candi
        GOOS=linux GOARCH=amd64 go build -o candi/candi-linux cmd/candi/*.go
        GOOS=darwin GOARCH=amd64 go build -o candi/candi-osx cmd/candi/*.go

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: candi
        path: candi
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Setup GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true

      - name: Get Artifact
      - uses: actions/download-artifact@master
        with:
          name: candi
          path: candi

      - name: Deploy
        run: |-
          gsutil -m rsync -R candi gs://agungdp/bin/candi
          gsutil acl ch -u AllUsers:R gs://agungdp/bin/candi
