name: Deploy

on:
  push:
    tags: [ v* ]

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GCP
        uses: google-github-actions/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true

      - name: Get Artifact
        uses: actions/download-artifact@master
        with:
          name: candi
          path: candi

      - name: Deploy
        run: |-
          gsutil -m rsync -R candi gs://agungdp/bin/candi
          gsutil acl -r ch -u AllUsers:R gs://agungdp/bin/candi
